[build]
  command = "npx ng build --configuration production"
  publish = "www"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
